#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
#
# Builds the zephyr-based equivalents of ot-rfsim's Thread-1.2 ot-cli-ftd_v12
# and ot-cli-mtd_v12 node executables.

set -euxo pipefail

main()
{
    mkdir -p ot-versions

    OTNS_NODE_TYPE="v12-ftd" OT_DEVICE_TYPE="ftd" OT_THREAD_VERSION="1_2" ./script/build "$@"
    ./script/install_exe v12-ftd ot-cli-ftd_v12

    OTNS_NODE_TYPE="v12-mtd" OT_DEVICE_TYPE="mtd" OT_THREAD_VERSION="1_2" ./script/build "$@"
    ./script/install_exe v12-mtd ot-cli-mtd_v12
}

main "$@"
