#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
#
# Builds the zephyr-based equivalents of ot-rfsim's default ("latest",
# Thread 1.4) ot-cli-ftd and ot-cli-mtd node executables.

set -euxo pipefail

main()
{
    mkdir -p ot-versions

    OTNS_NODE_TYPE="latest-ftd" OT_DEVICE_TYPE="ftd" OT_THREAD_VERSION="1_4" ./script/build "$@"
    ./script/install_exe latest-ftd ot-cli-ftd

    OTNS_NODE_TYPE="latest-mtd" OT_DEVICE_TYPE="mtd" OT_THREAD_VERSION="1_4" ./script/build "$@"
    ./script/install_exe latest-mtd ot-cli-mtd
}

main "$@"
