#!/bin/bash

set -euxo pipefail

EXTRA_MTD_OPTIONS=(
    "-DCONFIG_OPENTHREAD_CSL_RECEIVER=y"
)
readonly EXTRA_MTD_OPTIONS

EXTRA_FTD_OPTIONS=(
    "-DCONFIG_OPENTHREAD_CSL_RECEIVER=y"
)
readonly EXTRA_FTD_OPTIONS

main()
{
    mkdir -p ot-versions

    OTNS_NODE_TYPE="v12-ftd" OT_DEVICE_TYPE="ftd" OT_THREAD_VERSION="1_2" ./script/build \
        "${EXTRA_FTD_OPTIONS[@]}" "$@"
    ./script/install_exe v12-ftd ot-cli-ftd_v12

    OTNS_NODE_TYPE="v12-mtd" OT_DEVICE_TYPE="mtd" OT_THREAD_VERSION="1_2" ./script/build \
        "${EXTRA_MTD_OPTIONS[@]}" "$@"
    ./script/install_exe v12-mtd ot-cli-mtd_v12
}

main "$@"
